### ISSUE TITLE
Clicking a device on neighbours/netmap results in 'Sorry, no such device is known.'

### ISSUE THREAD

**Issue by romale** [netdisco/netdisco#335]
And, i've "domain_suffix:" configured in deployment.yml

## Your Environment

* Netdisco version used: 2.36.8
* SNMP::Info version used:  2.36

**Comment by ollyg** [comment]
I wonder if this issue appeared in ba9da2d as the fix to 316.

**Comment by xavidpr4** [comment]
Same problem here, but only with some devices. See graph 1 of neighbour map when the mouse is not over any device, and graph 2, when it's over a devices that is working fine. Picture 3 shows a device have the bug.

Moreover, when you hover over some of this affected devices (for example _sw-parkingwtc-n-1_ in the next picture) in neighbours map, the relational links to neighbour devices show in blank so are invisible (see graph 3). And then if you click this device, it show the main page and the message "Sorry, no such device is known." (graph 4). 

However when you try to search the same device inside the search bar, it can find it, so it's inside the DB. (see graph 5)

![graph1](https://user-images.githubusercontent.com/30469741/28624354-33c95994-7219-11e7-9412-8e2f8b71230a.PNG)
![graph2](https://user-images.githubusercontent.com/30469741/28624356-33d0c0d0-7219-11e7-8393-3942eb41168a.PNG)
![graph3](https://user-images.githubusercontent.com/30469741/28624355-33cf458e-7219-11e7-9ad8-ffb959353726.PNG)
![graph4](https://user-images.githubusercontent.com/30469741/28624358-341030b2-7219-11e7-9ecb-7a149b980e90.PNG)
![graph5](https://user-images.githubusercontent.com/30469741/28624357-33d2bbec-7219-11e7-8755-fd95d2a50a19.PNG)


By the way, I also configured domain_suffix in deployment.yml.

**Comment by ollyg** [comment]
Thanks @romale !

Fixed in 8f388bc.

**Comment by xavidpr4** [comment]
I've changed the file "/home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/views/ajax/device/netmap.tt" and now it looks like your fix.
I confirm that I can click to any device and the message "Sorry, no such device is know" doesn't shows anymore, but I'm still getting blank lines when hover some devices in neighbours map instead of remarking the relationships.

Look at my screenshots picture 3.

Thanks in advance!!

**Comment by romale** [comment]
I've blank lines too ...

**Comment by ollyg** [comment]
OK - I missed this because you put two issues into one ticket. Please don't do that!

I've committed changes d2c50e9 which I believe fix this (and also reengineer some of the netmap to work a little better).

**Comment by xavidpr4** [comment]
Uoops, sorry Ollyg, In the first moment I thought that was the same issue because only devices with blank lines were showing the message _"Sorry, no such device is know"_ when clicking on them.

Sorry for the inconvenience.

**Comment by ollyg** [comment]
No worries :-). I have pushed Netdisco 2.036009 to CPAN now. Thanks for your help.

**Comment by romale** [comment]
I've updated to Netdisco 2.036009, worked fine.
thanks @ollyg !
