### ISSUE TITLE
New errors in 2.39.23 in log and jobs

### ISSUE THREAD

**Issue by Linwood-F** [netdisco/netdisco#406]
Installed 2.39.23 after upgrading from 2.39.17 and am starting to see errors in the job queue (red tint and hover shows errors) and in the log.  Different errors.

## Expected Behavior
No errors and info now lost come back.  😀 

## Current Behavior

After install I restarted the backend and apache, then subnet discover-all and all other jobs from admin. Most finished fine., but some unexpectedly gave errors.

```
Use of uninitialized value $leaf in regexp compilation at /home/netdisco/perl5/lib/perl5/SNMP/Info.pm line 4370.
(Five of the above)
[178472] 2018-04-21 15:18:23 error bless( {'msg' => '{UNKNOWN}: Can\'t call method "update" on an undefined value at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 223, <__ANONIO__$
'}, 'DBIx::Class::Exception' )
[178456] 2018-04-21 15:18:53 error bless( {'msg' => '{UNKNOWN}: Can\'t call method "update" on an undefined value at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 223, <__ANONIO__$
'}, 'DBIx::Class::Exception' )

```

The other error I am getting, on various switches, is this: 

`Can't use string ("192.168.1.142") as hash ref while "strict refs" in use at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/NodePM line 117, <__ANONID__> line 1.
`

I'm seeing it for sure on Cisco and DLink and Netgear and Unifi switch.  There are no records in the admin table from before the update, but as I discovered it apparently is not a log, just the last run, so I cannot say for sure if these were here before.  I don't think so due to the missing port connected information.

The error above came from a Cisco 3650, and 192.168.1.142 is a HP Server connected directly on a Gigabit ethernet port.  That device is connected on port 1/0/22 and in the port display I see the MAC address of the server (as well as it's IP and Netbios name).   I deleted it did a discover again. This time the port showed nothing under "connected"; arpnip, macsuck and discover completed.  I don't see a nbtstat in the job queue display. 

Perhaps a bit more strange, when it did the discover it put 49.55.50.46 in the queue three times.   That's a weird address in Asia.  I don't see it in the arp table on that device anywhere, and not sure where Netdisco found it (and would like to know).  The four entries showed discover-error three times with a "duplicate" and once it just sat queued.

So I manually requested an nbtstat run for that device from the GUI.  It finished without error (1) but the port still shows no information.

So I'm not sure what is happening but I think I've lost my ability to see connected hosts based on MAC or ARP (I'm a bit hazy how it finds them, but specifically CDP/LLDP is working fine, the issues are with things like windows servers).  I also ran a discover for the connected HP server; as expected given Microsoft it gave no connected info (but no errors).

Interestingly the admin table now does NOT have the 192.168.1.1 error in it any more.  So it must think it only keep the last run.  But even though it ran successfully, I still have no information at all about connected device/mac/nbt information for that port, and it had very complete info before.

The device is not in the SNMP connect failure table; it is in the device_skip table with actionset=0, deferrals=0, last_defer=null.   Thinking this had something to do with it, I delete the row, and queued a NBTstat, Macsuck, arpnip, and Discover job (in that order) for it.   They all show completed, the 49.55.50.46 discover queued again, and the port info has no info on it again.

And I still don't know where 49.55.50.46 came from -- is there a way to find that out?  I'm certain that was not showing up and error'ing out before.  I realize it MIGHT be just an address someone accessed, but I would have expected to see it in a SHOW IP ARP on the switch, and did not.  Putting that in the find field says "no matching records" -- I would expect it to tell me where it came from if it saw it as part of its discovery. 

## Possible Solution
Not researched.

## Steps to Reproduce (for bugs)

There are a bunch of switches that gave this.  I'm more concerned that they eventually run correctly but do not yield information previously there.

I don't know what to run to debug, since it is inconsistent in when it gives errors, and the real problem is lack of information that was there, but that I am not certain the source of (to debug).  So am more than happy to run debugs or such.

## Your Environment
Ubuntu 16.04.4 (on a HyperV) 
Fresh upgrade to 2.39.23
SNMP 3.55
DB 52
Postgresql 9.5.12
Perl 5.22.1

Cisco's are all very current, the DLInk's are ancient, the Netgears maybe 1-3 years old, so there's a big variety giving errors.

**Comment by Linwood-F** [comment]
Hmmm... that IP address of 49.55.50.46 -- it's the decimal equivalent of 172., which is the beginning of many IP addresses I have on various interfaces, so I think there's some kind of mis-interpretation happening perhaps, where it's taking a character string and interpreting as binary.

**Comment by jeneric** [comment]
I think there are multiple issues here. The warning "Use of uninitialized value $leaf in regexp compilation at /home/netdisco/perl5/lib/perl5/SNMP/Info.pm line 4370." is due to a bug in the SNMP::Info module. A fix has been committed and should be available shortly in CPAN as version 3.56. I believe this would have manifested itself with the DLink devices. Please upgrade your SNMP::Info and let us know what issues remain.

**Comment by ollyg** [comment]
The address 49.55.50.46 is likely coming from a strange presentation of Neighbor IP that one of your devices is giving. You should see this in the log if you run a discover with debug enabled:

`bin/netdisco-do discover -d 1.2.3.4 -D`

**Comment by ollyg** [comment]
Sorry, I meant to add that Netdisco will ask NetAddr::IP module to interpret the neighbor IP and in this case it seems to come up with something wrong. If the source data is not useful, then I guess the error (additional job in the queue) is benign. If the neighbor IP is readable then maybe SNMP::Info needs amending to translate.

**Comment by Linwood-F** [comment]
@jeneric the new SNMP::info did get rid of the error log entries, but did not affect the other issues.  More on those after a bit more testing, but they are definitely still occurring.

**Comment by Linwood-F** [comment]
@ollyg the bogus addresses are appearing in the debug run here (I am including a section above that looks right):

```
[214241] 2018-04-22 15:55:34 debug -> run worker main/neighbors/100
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - setting manual topology links
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 192.168.1.201 with ID [84:c9:b2:19:51:68] on GigabitEthernet1/0/18
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 172.31.40.3 with ID [cc:8e:71:4e:86:00] on GigabitEthernet1/0/6
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 172.31.41.5 with ID [cc:8e:71:72:aa:80] on GigabitEthernet1/0/7
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 172.31.31.6 with ID [40:01:7a:c5:fc:00] on GigabitEthernet1/0/8
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 172.31.40.3 with ID [nameredacted] on GigabitEthernet1/0/6
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 172.31.41.5 with ID [nameredacted] on GigabitEthernet1/0/7
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 172.31.31.6 with ID [nameredacted] on GigabitEthernet1/0/8
[214241] 2018-04-22 15:55:34 debug  queue - skip: IP 172.31.40.3 is already queued from 192.168.1.1
[214241] 2018-04-22 15:55:34 debug  queue - skip: IP 172.31.41.5 is already queued from 192.168.1.1
[214241] 2018-04-22 15:55:34 debug  queue - skip: IP 172.31.31.6 is already queued from 192.168.1.1
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - processed 7 neighbors
[214241] 2018-04-22 15:55:34 debug -> run worker main/neighbors/100
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] queue - queued 49.55.50.46 for discovery (peer)
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] queue - queued 49.57.50.46 for discovery (peer)
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] queue - queued 49.55.50.46 for discovery (peer)
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] queue - queued 49.55.50.46 for discovery (peer)
[214241] 2018-04-22 15:55:34 debug  [192.168.1.1] neigh - 4 peers added to queue.
```

I THINK they are coming from the LLDP check, as there are three LLDP neighbors with 172. addresses and one LLDP with a 192 address, matching the above.

~$ netdisco-do show -d 192.168.1.1 -e lldp_ip
[241390] 2018-04-22 16:08:19  info App::Netdisco version 2.039023 loaded.
[241390] 2018-04-22 16:08:19  info show: [192.168.1.1]/lldp_ip started at Sun Apr 22 11:08:19 2018
\ {
    0.6.25   "172.31.40.3",
    0.7.24   "172.31.41.5",
    0.8.21   "172.31.31.6",
    0.18.7   "192.168.1.201"
}

This switch and its setup pre-dated the upgrade to the new version, and worked before. 

But what's more important to me, and could be completely unrelated -- the port displays are not showing MAC/IP addresses in the non-CDP, non-LLDP connected devices.  IN the past I would get, as an example, windows devices showing there.  Now they do not (more precisely they do for old devices -- a run is not removing them, but when I delete a device and re-discover (all four jobs) they do not come back, they are gone seemingly forever.  That's the real issue here, not the above (unless the above is causing it somehow, which I do not think it is). 

I do not know where these items come from -- nbtstat?  macsuck?  arpnip?   But there is also definitely a failure occurring on many (most?  all?) of the nbtstat runs, for all types of devices, and that's the hash ref error in the original posting.  

So my GUESS is there were three or four issues: 

- log file - fixed with the above mentioned new SNMP::Info

- bogus neighbor IP's for discover

- nbtstat job errors (hash reference)

- Missing port MAC/IP information on Cisco (maybe other) devices for attached, non-LLDP/CDP devices

It's the latter that to me is a show stopper, but I do not even know where it used to get that info.  But it's not getting it now.  I'm not even sure NBTSTAT has meaning against a cisco, though that's the job that is giving the error, making me suspect a connection.

Is there some debug I can run that would show where it is supposed to pull that info?

**Comment by ollyg** [comment]
Yes, this should work:

````
cd ~netdisco
bin/netdisco-backend stop
bin/netdisco-web stop
rm -rf perl5
curl -L https://cpanmin.us/ | perl - --notest --local-lib ~/perl5 https://cpan.metacpan.org/authors/id/O/OL/OLIVER/App-Netdisco-2.039017.tar.gz
bin/netdisco-backend start
bin/netdisco-web start
````

**Comment by Linwood-F** [comment]
Well, maybe, sort of.  It ran fine, it is now somewhat different (e.g. the ascii vs binary discovery no longer happens), but I'm showing 2.39.23 in the home page under version, and I'm getting mis-matched versions messages in the log - not sure if that's a problem or just a warning).

But more importantly I still am not getting any MAC/IP's in the connected devices column.

Is there some way I can debug that?   Specifically as an example I'm looking for windows servers mac/ip to appear there as they did before.  What process finds them?

**Comment by Linwood-F** [comment]
PS. I should have said thank you for the commands. 😄

**Comment by Piotrek-X** [comment]
I have seen that same behavior on my side. 
Found the problem within the SNMP::Info module (ver 3.56).
I replaced the SNMP folder (/perl5/lib/perl5/SNMP) with a older Version.

**Comment by Piotrek-X** [comment]
that worked too:
cpanm --reinstall -l ~/perl5 http://cpan.metacpan.org/authors/id/O/OL/OLIVER/SNMP-Info-3.53.tar.gz

**Comment by Linwood-F** [comment]
@Piotrek-X thanks for the command, I always struggle with cpan

**Comment by Piotrek-X** [comment]
In my case Netdisco didn't see any nodes connected to Switchports after the update to 2.39.24
The "last seen" timer for known nodes went up and new nodes would not been found.

**Comment by jeneric** [comment]
@Piotrek-X based upon your feedback identified an issue introduced in 3.55 that prevented macsuck from working on Cisco devices. The fix has been incorporated into 3.57 which was just pushed to CPAN.

**Comment by jeneric** [comment]
@Linwood-F once gain I'm not sure if the 3.57 fix will resolve all your issues. The [netdisco-do]( https://metacpan.org/pod/distribution/App-Netdisco/bin/netdisco-do ) command line tool can be helpful to investigate. Run macsuck, arpnip, and nbtstat against the problematic nodes with the -DI or -DII flags.

**Comment by Piotrek-X** [comment]
Thanks for the fix. 
Reinstalled the Module with 
cpanm --reinstall -l ~/perl5 SNMP::Info

**Comment by ollyg** [comment]
Hi @Linwood-F thanks for the additional debug output! The strange neighbor address is actually coming from the dynamic routing tables on the device. Can you supply the following output?

````
netdisco-do show -d 192.168.1.1 -D -e bgp_peer_addr
netdisco-do show -d 192.168.1.1 -D -e ospf_peers
netdisco-do show -d 192.168.1.1 -D -e eigrp_peers
````

(the debug log line you saw is from this file: https://github.com/netdisco/netdisco/blob/master/lib/App/Netdisco/Worker/Plugin/Discover/Neighbors/Routed.pm)

regards,
oliver.

**Comment by Linwood-F** [comment]
@ollyg I'll pull these later this morning, thanks for narrowing it down, but it sounds worthwhile grabbing the new SNMP to see what it does.  We use eigrp.

I'm still much less concerned with those, which are kind of cosmetic, than the loss of the other items, e.g. wherever it pulls the presence of (for example) a windows server hooked on, or through, a port.  Those are very valuable and just gone now.  I know those are not lldp or cdp, can you tell me what pulls those in, what kind of debug I would run to tell what's happening there?

**Comment by ollyg** [comment]
@Linwood-F have you upgraded SNMP::Info? We just released a bug fix which is important to this ticket. You can also get it with an App::Netdisco upgrade.

**Comment by Linwood-F** [comment]
OK, the bogus addresses are coming from eigrp neighbors: 

```
$ netdisco-do show -d 192.168.1.1 -D -e eigrp_peers
[5827] 2018-04-27 13:33:59  info App::Netdisco version 2.039025 loaded.
[5827] 2018-04-27 13:34:00  info show: [192.168.1.1]/eigrp_peers started at Fri Apr 27 08:34:00 2018
[5827] 2018-04-27 13:34:00 debug show: running with timeout 600s
[5827] 2018-04-27 13:34:00 debug => running workers for phase: check
[5827] 2018-04-27 13:34:00 debug -> run worker check/_base_/0
[5827] 2018-04-27 13:34:00 debug Show is able to run
[5827] 2018-04-27 13:34:00 debug => running workers for phase: main
[5827] 2018-04-27 13:34:00 debug -> run worker main/_base_/100
[5827] 2018-04-27 13:34:00 debug snmp reader cache warm: [192.168.1.1]
[5827] 2018-04-27 13:34:00 debug [192.168.1.1:161] try_connect with ver: 2, class: SNMP::Info::Layer3::C6500, comm: <hidden>
\ {
    65536.10.1   "49.57.50.46",
    65536.10.4   "49.55.50.46"
}
[5827] 2018-04-27 13:34:00  info show: finished at Fri Apr 27 08:34:00 2018
[5827] 2018-04-27 13:34:00  info show: status done: Showed eigrp_peers response from 192.168.1.1

```

What's odd about that is they are coming from only two of the routers -- a Cisco 3650 running 3.7.5 IOS-XE, which is pretty current.  The others (3560CX) are yielding the right address, and they are using the SNMP::Info::Layer3::C3550 class.   

It looks like this may actually be a Cisco thing, or at least a variation in the return format, here is the failing 3650: from an snmpwalk:

CISCO-SMI::ciscoMgmt.449.1.4.1.1.2.65536.10.1 = INTEGER: 1
CISCO-SMI::ciscoMgmt.449.1.4.1.1.2.65536.10.4 = INTEGER: 1
CISCO-SMI::ciscoMgmt.449.1.4.1.1.3.65536.10.1 = STRING: "192.168.1.132"
CISCO-SMI::ciscoMgmt.449.1.4.1.1.3.65536.10.4 = STRING: "172.31.31.6"

And here's one from a working 3560: 

CISCO-SMI::ciscoMgmt.449.1.4.1.1.2.65536.10.0 = INTEGER: 1
CISCO-SMI::ciscoMgmt.449.1.4.1.1.2.65536.10.1 = INTEGER: 1
CISCO-SMI::ciscoMgmt.449.1.4.1.1.2.65536.10.2 = INTEGER: 1
CISCO-SMI::ciscoMgmt.449.1.4.1.1.2.65536.10.3 = INTEGER: 1
CISCO-SMI::ciscoMgmt.449.1.4.1.1.3.65536.10.0 = Hex-STRING: AC 1F 17 06
CISCO-SMI::ciscoMgmt.449.1.4.1.1.3.65536.10.1 = Hex-STRING: AC 10 0B 02
CISCO-SMI::ciscoMgmt.449.1.4.1.1.3.65536.10.2 = Hex-STRING: AC 10 0C 04
CISCO-SMI::ciscoMgmt.449.1.4.1.1.3.65536.10.3 = Hex-STRING: AC 1F 19 0A

The actual returned values are correct in that they are flagged as hex vs string properly, but clearly there's a format change.  We plan to which the code line from MD to Denali on the 3650's soon, so I am curious if they will change.  

I THINK though, that this is a change in the SNMP info routine somewhere, as I am pretty sure this used to work.   My GUESS is that they changed interpretation of those strings? 

But I also think in this case it's more cosmetic than functional, since it's getting the neighbors from CDP and LLDP as well.

Off to see if the new versions affected the other issues.  Maybe should have done separate issues for each.

Shall I keep this thread specific to the hex vs ascii strings, and if the other issues still occur separate?

**Comment by Linwood-F** [comment]
OK, here's the one that's killing NBTSTAT (though I do not know if that is functional as not sure if NBTSTAT can run against switches anyway really):

```
$ netdisco-do nbtstat -d the3560cxswitchname -D
[54782] 2018-04-27 13:56:42  info App::Netdisco version 2.039025 loaded.
[54782] 2018-04-27 13:56:42  info nbtstat: [192.168.15.1] started at Fri Apr 27 08:56:42 2018
[54782] 2018-04-27 13:56:42 debug nbtstat: running with timeout 600s
[54782] 2018-04-27 13:56:42 debug => running workers for phase: check
[54782] 2018-04-27 13:56:42 debug -> run worker check/_base_/0
[54782] 2018-04-27 13:56:42 debug Nbtstat is able to run.
[54782] 2018-04-27 13:56:42 debug => running workers for phase: main
[54782] 2018-04-27 13:56:42 debug -> run worker main/core/0
[54782] 2018-04-27 13:56:43 debug -> Can't use string ("10.150.0.202") as a HASH ref while "strict refs" in use at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Node.pm line 117.
[54782] 2018-04-27 13:56:43 debug Can't use string ("10.150.0.202") as a HASH ref while "strict refs" in use at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Node.pm line 117.
[54782] 2018-04-27 13:56:43  info nbtstat: finished at Fri Apr 27 08:56:43 2018
[54782] 2018-04-27 13:56:43  info nbtstat: status error: Can't use string ("10.150.0.202") as a HASH ref while "strict refs" in use at /home/netdisco/perl5/lib/perl5/App/Netdisco/Util/Node.pm line 117.
$
```

This definitely started in the timeframe of the current release, and is giving the error on all switches I have tried it against, Cisco, DLink, etc.

**Comment by Linwood-F** [comment]
With the last change the macsuck (I think that's where it comes from) is working better in terms of finding hosts on switch ports.    I'm not quite sure how, as I ran it in debug and got this.

For a  3650 Cisco with an access port configured for a windows 2016 host.  The port configuration is this:

```
interface GigabitEthernet1/0/22
 description HP Server NIC 1 for host
 switchport access vlan 192
 spanning-tree portfast
end

```

When I run macsuck in debug (among other stuff): 

```
[73527] 2018-04-27 14:05:27 debug  [192.168.1.1] macsuck 40:a8:f0:22:c2:f7 - port GigabitEthernet1/0/22 is detected uplink - skipping.
[73527] 2018-04-27 14:05:27 debug  [192.168.1.1] macsuck - port GigabitEthernet1/0/22 vlan 192 : 1 nodes

```

But it's coming out nicely as follows; 

Possible Uplink:
40:a8:f0:22:c2:f7
host fqdn
(192.168.1.142)  << correct IP for host.

I deleted the host and let it re-discover to make sure everything found was fresh.

These were missing before, so I am guessing the SNMP changes fixed the problem.  Not sure how it determined it was an uplink though, it shouldn't have seen it as a neighbor via any protocols.  BUt the important thing is that it is showing the host again, which it did not.  To me this is by far the biggest problem, and now appears fixed, even if I do not quite know where they come from.

**Comment by jeneric** [comment]
Based upon your feedback it looks like the SNMP::Info 3.57 release fixed the macsuck issue.

I have opened [Issue 261](https://github.com/netdisco/snmp-info/issues/261) within the snmp-info project to address the return values from the EIGRP neighbors. Gathering EIGRP neighbors for discovery was a recently added feature to Netdisco which is why you didn't see this before.

Thanks for the detailed information to help us track these problems down.

**Comment by ollyg** [comment]
@Linwood-F I would search for MAC `40:a8:f0:22:c2:f7` and see if it comes out anywhere other than on that port. The log of "possible uplink" means that the MAC has been seen elsewhere, I think.

**Comment by ollyg** [comment]
Hi @Linwood-F I've pushed a new version of Netdisco with a fix for the NBTStat issue - please test this and let us know how you get on. I will close this ticket now as I think we've addressed all issues raised. Please open a new one if you find something else. Many thanks!!

**Comment by Linwood-F** [comment]
@ollyg thanks, the errors are gone.

As to the MAC address I see how it is appearing, but it is bogus, but probably microsoft's fault.  It appears on four different interfaces on the phone host -- the ethernet interface (correct), but then also the Ethernet-QOS Packet Schedler, the Ethernet-WFP 802.3 MAC Layer Lightweight Filter, and the Ethernet WFP Native MAC Layer Lightweight Filter.    Not sure if it's practical to really know those are all the same thing.

**Comment by Linwood-F** [comment]
I'm feeling stupid.  No matter what I put in there nothing changes.  I'm starting and stopping the netdisco-daemon service after the change.  I've tried simpler and more explicit tests, tried exactly what you had (is the ? in the word scheduler a typo?), but basically nothing changes.  Is there some magic to making it work?   It's just a regex, no start/end line required or such right?   Is there some magic to deploying it?   I do not have ignore_interfaces in my deployment.yml at all, so the one in config rules? 

I'm changing /perl5/lib/perl5/auto/share/dist/App-Netdisco/config.yml

Here's the last change I tried, for example, trying to be very explicit: 

`  - 'Blade-Aggregation\d'
  - 'M-GigabitEthernet\d/\d/\d'
  - 'Ethernet.*QoS Packet Scheduler'
  - 'Ethernet.*MAC Layer LightWeight'
ignore_private_nets: false
`

**Comment by jeneric** [comment]
@Linwood-F, the bogus return values from the EIGRP neighbors should be resolved in SNMP::Info 3.61 which has just been pushed to CPAN.

**Comment by Linwood-F** [comment]
@jeneric that's great though I have confused myself somewhere, as the problem went away.  I'm not sure if it was a new version from Netdisco (I'm at 2.39.27) or snmp (I'm at 3.57), or it was our upgrade of the Cisco's themselves from the older code line (3.7.5) to newer Denali (necessary for other reasons).  But the problem no longer shows up.  I certainly appreciate the change and the head's up, but I will be unable to confirm if it fixes it as I can no longer reproduce.  But thank you!
